import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./components/common/Navbar/Navbar";
import { BgWrapper } from "./components/common/BgWrapper/BgWrapper";

export const metadata: Metadata = {
  title: "Coffee Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BgWrapper>
          <Navbar />
          {children}
        </BgWrapper>
      </body>
    </html>
  );
}
